plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  rubocop-rails: config/default.yml
  rubocop-rspec: config/default.yml
  rubocop-rspec_rails: config/default.yml

AllCops:
  Exclude:
    - 'app/javascript'